/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafica;

import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import dao.Jugador;
import dao.peon;
import dao.Cuadricula;
import dao.serverListener;
import javax.swing.JLabel;
/**
 *
 * @author Cristhian Quiroga
 */
public class chess extends javax.swing.JFrame{
    Component fichaSel;
    public JLabel buffLbl;
    /**
     * Creates new form chess
     */
    
    public chess() {
        initComponents();
        
        //serverListener R1;
        //R1 = new serverListener(jLabel1);
        //R1.start();

        Jugador p1 = new Jugador("Kronoz", "asdasd", "asdasdasd", 1);
        Cuadricula[] cuadriculas = new Cuadricula[64];
        peon[] peones = new peon[8];
        
        char letra = 97;
        for(int i = 0; i<8; i++){
            peones[i] = new peon(p1, "Peon"+i, letra+"7", jLabel1);
            letra++;
        }
        
        
        letra = 97;
        int numero = 8;
        int cont = 0;
        
        for(int i = 0; i<64; i++){
            
            JPanel panel = new javax.swing.JPanel();
            if(cont%2 == 0)panel.setBackground(new java.awt.Color(255, 255, 255));
            else panel.setBackground(new java.awt.Color(0, 0, 0));
            panel.setLayout(new java.awt.GridBagLayout());
            panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
            cuadriculas[i] = new Cuadricula();
            cuadriculas[i].setNombre(letra + "" + numero);
            cuadriculas[i].setPanel(panel, jLabel1, tablero, peones, cuadriculas);
            
            letra++;
            cont++;
            if(letra > 104){
                numero--;
                letra = 97;
                cont++;
            } 
            tablero.add(cuadriculas[i].getPanel());
        }
        
        
        cuadriculas[8].getPanel().add(peones[0].crearFicha(buffLbl, cuadriculas));
        cuadriculas[9].getPanel().add(peones[1].crearFicha(buffLbl, cuadriculas));
        cuadriculas[10].getPanel().add(peones[2].crearFicha(buffLbl, cuadriculas));
        cuadriculas[11].getPanel().add(peones[3].crearFicha(buffLbl, cuadriculas));
        cuadriculas[12].getPanel().add(peones[4].crearFicha(buffLbl, cuadriculas));
        cuadriculas[13].getPanel().add(peones[5].crearFicha(buffLbl, cuadriculas));
        cuadriculas[14].getPanel().add(peones[6].crearFicha(buffLbl, cuadriculas));
        cuadriculas[15].getPanel().add(peones[7].crearFicha(buffLbl, cuadriculas));
        
        SwingUtilities.updateComponentTreeUI(this);
        //JOptionPane.showMessageDialog(null, j.WIDTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tablero = new javax.swing.JPanel();
        jPanel66 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tablero.setBackground(new java.awt.Color(0, 0, 0));
        tablero.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tablero.setPreferredSize(new java.awt.Dimension(630, 630));
        tablero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableroMouseClicked(evt);
            }
        });
        tablero.setLayout(new java.awt.GridLayout(8, 8));

        jPanel66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 296, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 265, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(85, 85, 85))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel66, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addComponent(tablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        Jugador p1 = new Jugador("Crico", "asdasd", "asdasdasd", 1);
//        peon po1 = new peon(p1, "Peon", "b7", peon, new javax.swing.ImageIcon(getClass().getResource("/assets/Peon.png")));
//        b7.add(po1.crearFicha(), new java.awt.GridBagConstraints());
        SwingUtilities.updateComponentTreeUI(this);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tableroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableroMouseClicked
       
    }//GEN-LAST:event_tableroMouseClicked
   
    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked
    public void mover(JPanel cuadricula){
        if(fichaSel != null){
            cuadricula.add(fichaSel);
            SwingUtilities.updateComponentTreeUI(this);
        }
        fichaSel = null;
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chess.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new chess().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel tablero;
    // End of variables declaration//GEN-END:variables

 
}
